class NetworkException(Exception):
    pass


class AuthException(Exception):
    pass
